In [71]:
import pandas as pd

df = pd.read_csv('data/Indonesian_Food_Recipes.csv')

In [73]:
import re

def clean_ingredients(text):
    text = text.lower()
    
    # hapus angka & satuan
    text = re.sub(r'\d+|\b(gr|kg|sdm|sdt|buah|butir|lembar|siung)\b', '', text)
    
    # ganti separator
    text = text.replace('--', ',')
    
    # hapus karakter aneh
    text = re.sub(r'[^a-zA-Z, ]', '', text)
    
    # split jadi list
    items = text.split(',')
    
    # bersihkan spasi
    items = [i.strip() for i in items if i.strip() != '']
    
    return items

In [74]:
df['Ingredients Cleaned'] = df['Ingredients'].apply(clean_ingredients)

In [75]:
df[['Title','Ingredients Cleaned']].head(10)

,Title,Ingredients Cleaned
0,Ayam Woku Manado,"[ekor ayam kampung potong, jeruk nipis, garam,..."
1,Ayam goreng tulang lunak,"[ayam dipotong sesuai selera jangan kecil ya, ..."
2,Ayam cabai kawin,"[ayam, cabai hijau besar, cabai merah rawit, b..."
3,Ayam Geprek,"[daging ayam saya pakai fillet, secukupnya gul..."
4,Minyak Ayam,"[kulit ayam lemaknya, bawang putih kating, ci..."
5,Nasi Bakar Ayam,"[piring nasi, fillet ayam, potong kotak, cuci ..."
6,Ayam Saus Hintalu Jaruk,"[ekor ayam, hintalu jaruk, cabe merah, cabe hi..."
7,Ayam saos teriyaki Lada Hitam,"[ayam bagian dada dan tulang, bawang bombay, b..."
8,Steak ayam,"[dada ayam fillet, air jeruk nipis, secukupnya..."
9,Ayam Saos Asam Manis Simple,"[ayam bagian dada fillet potong dadu, secukupn..."

In [76]:
stopwords = [
    'secukupnya', 'sesuai', 'selera', 'potong', 'dipotong',
    'cuci', 'dadu', 'iris', 'fillet', 'bagian', 'gunakan'
]

def clean_items(items):
    cleaned = []
    for item in items:
        words = item.split()
        
        # ambil 2 kata pertama saja (biar tidak jadi kalimat panjang)
        item_clean = ' '.join(words[:2])
        
        # buang stopwords
        if item_clean not in stopwords:
            cleaned.append(item_clean)
    
    return cleaned

In [77]:
df['Ingredients Cleaned'] = df['Ingredients Cleaned'].apply(clean_items)

In [78]:
print(df['Ingredients'].iloc[1])

1 kg ayam (dipotong sesuai selera jangan kecil2 ya)--2 batang serai (memarkan)--4 lembar daun jeruk--7 butir bawang putih (haluskan)--1 sdm ketumbar (haluskan)--3 ruas jari Laos (haluskan)--3 ruas jari kunyit (haluskan)--2 butir kemiri (haluskan)--secukupnya Garam--Secukupnya Air (tuk ukep ayam)--Secukupnya Minyak goreng--

In [79]:
print(df['Ingredients Cleaned'].iloc[1])

['ayam dipotong', 'batang serai', 'daun jeruk', 'bawang putih', 'ketumbar haluskan', 'ruas jari', 'ruas jari', 'kemiri haluskan', 'secukupnya garam', 'secukupnya air', 'secukupnya minyak']

In [80]:
import re

remove_words = [
    'dipotong', 'potong', 'haluskan', 'secukupnya',
    'ruas', 'jari', 'batang'
]

def clean_items(items):
    cleaned = []
    
    for item in items:
        words = item.split()
        
        # buang kata yang tidak penting
        words = [w for w in words if w not in remove_words]
        
        if len(words) == 0:
            continue
        
        # ambil max 2 kata (biar tetap "cabai merah")
        cleaned_item = ' '.join(words[:2])
        
        cleaned.append(cleaned_item)
    
    return cleaned

In [81]:
df['Ingredients Cleaned'] = df['Ingredients Cleaned'].apply(clean_items)

In [82]:
print(df['Ingredients Cleaned'].iloc[1])

['ayam', 'serai', 'daun jeruk', 'bawang putih', 'ketumbar', 'kemiri', 'garam', 'air', 'minyak']

In [83]:
df['Ingredients Cleaned'] = df['Ingredients Cleaned'].apply(lambda x: list(set(x)))

In [84]:
print(df['Ingredients Cleaned'].iloc[1])

['daun jeruk', 'garam', 'ketumbar', 'air', 'bawang putih', 'minyak', 'kemiri', 'ayam', 'serai']

In [85]:
df['ingredients_join'] = df['Ingredients Cleaned'].apply(lambda x: ' '.join(x))

In [86]:
df.head()

,Title,Ingredients,Steps,Loves,URL,Category,Title Cleaned,Total Ingredients,Ingredients Cleaned,Total Steps,ingredients_join
0,Ayam Woku Manado,1 Ekor Ayam Kampung (potong 12)--2 Buah Jeruk ...,1) Cuci bersih ayam dan tiriskan. Lalu peras j...,1,https://cookpad.com/id/resep/4473027-ayam-woku...,ayam,ayam woku manado,14,"[cabe rawit, ikat daun, garam, sereh, daun sal...",7,cabe rawit ikat daun garam sereh daun salam ba...
1,Ayam goreng tulang lunak,1 kg ayam (dipotong sesuai selera jangan kecil...,"1) Haluskan bumbu2nya (BaPut, ketumbar, kemiri...",1,https://cookpad.com/id/resep/4471956-ayam-gore...,ayam,ayam goreng tulang lunak,11,"[daun jeruk, garam, ketumbar, air, bawang puti...",5,daun jeruk garam ketumbar air bawang putih min...
2,Ayam cabai kawin,1/4 kg ayam--3 buah cabai hijau besar--7 buah ...,1) Panaskan minyak di dalam wajan. Setelah min...,2,https://cookpad.com/id/resep/4473057-ayam-caba...,ayam,ayam cabai kawin,10,"[garam, gula, air, bawang putih, minyak, cabai...",3,garam gula air bawang putih minyak cabai merah...
3,Ayam Geprek,250 gr daging ayam (saya pakai fillet)--Secuku...,1) Goreng ayam seperti ayam krispi\n2) Ulek se...,10,https://cookpad.com/id/resep/4473023-ayam-geprek,ayam,ayam geprek,7,"[daging ayam, gula, kol, minyak, tepung ayam, ...",3,daging ayam gula kol minyak tepung ayam timun ...
4,Minyak Ayam,400 gr kulit ayam & lemaknya--8 siung bawang p...,1) Cuci bersih kulit ayam. Sisihkan\n2) Ambil ...,4,https://cookpad.com/id/resep/4427438-minyak-ayam,ayam,minyak ayam,5,"[ketumbar bubuk, cincang kasar, geprek, kulit ...",6,ketumbar bubuk cincang kasar geprek kulit ayam...

In [88]:
df.to_csv('resep_bersih.csv', index=False, encoding='utf-8')

In [89]:
import re

# stopwords khusus resep
recipe_stopwords = {
    "ikat", "secukupnya", "sesuai", "selera",
    "cincang", "halus", "kasar", "geprek",
    "memarkan", "iris", "tipis", "potong",
    "dadu", "serong", "lembar", "buah",
    "butir", "siung", "sendok", "sdt", "sdm",
    "gram", "kg", "ml", "liter", "cup",
    "gelas", "bungkus", "batang", "ruas",
    "ambil", "kupas", "cuci", "rebus",
    "goreng", "sangrai", "parut", "untuk",
    "tambahan", "taburan"
}

def final_clean(text):
    if pd.isna(text):
        return ""

    text = str(text).lower()

    # hapus simbol
    text = re.sub(r"[^a-zA-Z\s]", " ", text)

    # rapikan spasi
    text = re.sub(r"\s+", " ", text).strip()

    words = text.split()

    # hapus stopwords
    cleaned = [word for word in words if word not in recipe_stopwords]

    # hapus duplikat kata
    cleaned = list(dict.fromkeys(cleaned))

    return " ".join(cleaned)

# buat kolom final
df["ingredients_final"] = df["ingredients_join"].apply(final_clean)

# cek hasil
print(df[["ingredients_join", "ingredients_final"]].head(10))

                                    ingredients_join  \
0  cabe rawit ikat daun garam sereh daun salam ba...
1  daun jeruk garam ketumbar air bawang putih min...
2  garam gula air bawang putih minyak cabai merah...
3  daging ayam gula kol minyak tepung ayam timun ...
4  ketumbar bubuk cincang kasar geprek kulit ayam...
5  kecap manis bawang putih kemiri cm serai minya...
6  bks merica gula garam dan jeruk nipis bawang p...
7  ayam bagian bungkus saos air bawang daun bawan...
8  maizena cairkan bawang putih kecap manis dada ...
9  bungkus tepung saos sambal ayam bagian gula to...

                                   ingredients_final
0  cabe rawit daun garam sereh salam bawang putih...
1  daun jeruk garam ketumbar air bawang putih min...
2  garam gula air bawang putih minyak cabai merah...
3  daging ayam gula kol minyak tepung timun lalap...
4  ketumbar bubuk kulit ayam bawang putih minyak ...
5  kecap manis bawang putih kemiri cm serai minya...
6  bks merica gula garam dan jeruk nipis bawang p...
7  ayam bagian saos air bawang daun putih cabe ij...
8  maizena cairkan bawang putih kecap manis dada ...
9  tepung saos sambal ayam bagian gula tomat uk a...

In [90]:
extra_stopwords = {
    "bks", "cm", "uk", "dan", "atau", "dengan",
    "bagian", "cairkan", "bubuk", "toping",
    "topping", "lalap", "kulit", "isi",
    "besar", "kecil", "sedang"
}

In [91]:
normalization = {
    "saos": "saus",
    "cabe": "cabai",
    "bamer": "bawang merah",
    "baput": "bawang putih"
}

In [92]:
import re

recipe_stopwords = {
    "ikat", "secukupnya", "sesuai", "selera",
    "cincang", "halus", "kasar", "geprek",
    "memarkan", "iris", "tipis", "potong",
    "dadu", "serong", "lembar", "buah",
    "butir", "siung", "sendok", "sdt", "sdm",
    "gram", "kg", "ml", "liter", "cup",
    "gelas", "bungkus", "batang", "ruas",
    "ambil", "kupas", "cuci", "rebus",
    "goreng", "sangrai", "parut", "untuk",
    "tambahan", "taburan",

    # tambahan final cleaning
    "bks", "cm", "uk", "dan", "atau",
    "dengan", "bagian", "cairkan",
    "bubuk", "toping", "topping",
    "lalap", "kulit", "isi",
    "besar", "kecil", "sedang"
}

normalization = {
    "saos": "saus",
    "cabe": "cabai",
    "bamer": "bawang merah",
    "baput": "bawang putih"
}

def final_clean_v2(text):
    if pd.isna(text):
        return ""

    text = str(text).lower()
    text = re.sub(r"[^a-zA-Z\s]", " ", text)
    text = re.sub(r"\s+", " ", text).strip()

    words = text.split()
    cleaned = []

    for word in words:
        # normalisasi
        word = normalization.get(word, word)

        # hapus stopwords
        if word not in recipe_stopwords:
            cleaned.append(word)

    # hapus duplikat
    cleaned = list(dict.fromkeys(cleaned))

    return " ".join(cleaned)

df["ingredients_final"] = df["ingredients_final"].apply(final_clean_v2)

print(df[["ingredients_final"]].head(10))

                                   ingredients_final
0  cabai rawit daun garam sereh salam bawang puti...
1  daun jeruk garam ketumbar air bawang putih min...
2  garam gula air bawang putih minyak cabai merah...
3  daging ayam gula kol minyak tepung timun lalap...
4             ketumbar ayam bawang putih minyak jahe
5  kecap manis bawang putih kemiri serai minyak t...
6  merica gula garam jeruk nipis bawang putih min...
7  ayam saus air bawang daun putih cabai ijo ment...
8  maizena bawang putih kecap manis dada ayam jam...
9  tepung saus sambal ayam gula tomat air bputih ...

In [93]:
print("Jumlah data sebelum:", len(df))

# hapus duplikat berdasarkan judul + bahan final
df = df.drop_duplicates(
    subset=["Title Cleaned", "ingredients_final"]
)

print("Jumlah data sesudah:", len(df))
print("Jumlah data terhapus:", 14945 - len(df))

Jumlah data sebelum: 14945
Jumlah data sesudah: 14939
Jumlah data terhapus: 6

In [94]:
df.to_csv("resep_final_ready.csv", index=False)
print("Dataset final sudah bersih dan siap TF-IDF")

Dataset final sudah bersih dan siap TF-IDF

In [95]:
df.to_csv("resep_final_ready.csv", index=False, encoding="utf-8-sig")

In [96]:
import pandas as pd
import ast

# =========================
# LOAD DATA
# =========================
df = pd.read_csv("resep_cleaned.csv")

# cek kolom
print(df.columns)


# =========================
# UBAH STRING LIST → LIST ASLI
# karena Ingredients Cleaned masih berbentuk string
# =========================
def convert_to_list(x):
    try:
        return ast.literal_eval(x)
    except:
        return []

df["Ingredients Cleaned"] = df["Ingredients Cleaned"].apply(convert_to_list)


# =========================
# DAFTAR NOISE YANG HARUS DIHAPUS
# =========================
noise_words = {
    "ikat", "gelas", "air", "ekor", "bagian",
    "bungkus", "bks", "cm", "ruas", "batang",
    "lembar", "buah", "butir", "siung",
    "sendok", "sdm", "sdt", "kg", "gram",
    "ml", "liter", "cup", "secukupnya",
    "sesuai", "selera", "untuk", "tambahan",
    "taburan", "penyedap rasa", "penyedap",
    "rasa", "cincang", "halus", "kasar",
    "geprek", "memarkan", "iris", "tipis",
    "potong", "dadu", "serong"
}


# =========================
# FUNGSI CLEANING FINAL
# =========================
def clean_ingredients_list(ingredients):
    cleaned = []

    for item in ingredients:
        item = str(item).lower().strip()

        # hapus noise phrase penuh
        if item in noise_words:
            continue

        # hapus kata noise di dalam phrase
        words = item.split()
        words = [w for w in words if w not in noise_words]

        # gabungkan ulang
        item = " ".join(words).strip()

        # skip jika kosong
        if item == "":
            continue

        # skip jika masih terlalu pendek
        if len(item) <= 2:
            continue

        cleaned.append(item)

    # hapus duplikat
    cleaned = list(dict.fromkeys(cleaned))

    return cleaned


# =========================
# PROSES CLEANING
# =========================
df["Ingredients Final"] = df["Ingredients Cleaned"].apply(clean_ingredients_list)


# =========================
# BUAT KOLOM UNTUK TF-IDF
# =========================
df["ingredients_join"] = df["Ingredients Final"].apply(lambda x: " ".join(x))


# =========================
# HAPUS DUPLIKAT RESEP
# =========================
df = df.drop_duplicates(
    subset=["Title Cleaned", "ingredients_join"]
)


# =========================
# SIMPAN FILE FINAL
# =========================
df.to_csv("resep_final_ready.csv", index=False, encoding="utf-8-sig")

print("SELESAI")
print("Dataset final siap untuk TF-IDF")

print(df[["Title Cleaned", "Ingredients Final", "ingredients_join"]].head(10))

Index(['Title', 'Ingredients', 'Steps', 'Loves', 'URL', 'Category',
       'Title Cleaned', 'Total Ingredients', 'Ingredients Cleaned',
       'Total Steps', 'ingredients_join'],
      dtype='str')
SELESAI
Dataset final siap untuk TF-IDF
                   Title Cleaned  \
0               ayam woku manado
1       ayam goreng tulang lunak
2               ayam cabai kawin
3                    ayam geprek
4                    minyak ayam
5                nasi bakar ayam
6        ayam saus hintalu jaruk
7  ayam saos teriyaki lada hitam
8                     steak ayam
9    ayam saos asam manis simple

                                   Ingredients Final  \
0  [cabe rawit, daun, garam, sereh, daun salam, b...
1  [daun jeruk, garam, ketumbar, bawang putih, mi...
2  [garam, gula, bawang putih, minyak, cabai mera...
3  [daging ayam, gula, kol, minyak, tepung ayam, ...
4  [ketumbar bubuk, kulit ayam, bawang putih, min...
5  [kecap manis, bawang putih, kemiri, serai, min...
6  [merica, gula, garam dan, jeruk nipis, bawang ...
7  [ayam, saos, bawang daun, bawang putih, cabe i...
8  [maizena cairkan, bawang putih, kecap manis, d...
9  [tepung, saos sambal, ayam, gula, tomat uk, bp...

                                    ingredients_join
0  cabe rawit daun garam sereh daun salam bawang ...
1  daun jeruk garam ketumbar bawang putih minyak ...
2  garam gula bawang putih minyak cabai merah baw...
3  daging ayam gula kol minyak tepung ayam timun ...
4  ketumbar bubuk kulit ayam bawang putih minyak ...
5  kecap manis bawang putih kemiri serai minyak t...
6  merica gula garam dan jeruk nipis bawang putih...
7  ayam saos bawang daun bawang putih cabe ijo me...
8  maizena cairkan bawang putih kecap manis dada ...
9  tepung saos sambal ayam gula tomat uk bputih m...

In [97]:
extra_noise = {
    "dan", "atau", "uk", "cairkan",
    "ijo", "bubuk", "bagian",
    "daun"
}

In [98]:
normalization = {
    "saos": "saus",
    "cabe": "cabai",
    "ijo": "hijau",
    "bputih": "bawang putih",
    "bmerah": "bawang merah",
    "cabe ijo": "cabai hijau"
}

In [99]:
print(df[["Title Cleaned", "Ingredients Final", "ingredients_join"]].head(20))

                             Title Cleaned  \
0                         ayam woku manado
1                 ayam goreng tulang lunak
2                         ayam cabai kawin
3                              ayam geprek
4                              minyak ayam
5                          nasi bakar ayam
6                  ayam saus hintalu jaruk
7            ayam saos teriyaki lada hitam
8                               steak ayam
9              ayam saos asam manis simple
10              mie ayam homemade by suami
11  ayam bakar pedas manis resep nila sari
12      semur ayam kentang ala mama kirana
13                              ayam suwir
14                      ayam goreng tepung
15                 tulang ayam pedas manis
16                     ayam penyet rumahan
17                                sop ayam
18                              ayam suwir
19                   nugget ayam home made

                                    Ingredients Final  \
0   [cabe rawit, daun, garam, sereh, daun salam, b...
1   [daun jeruk, garam, ketumbar, bawang putih, mi...
2   [garam, gula, bawang putih, minyak, cabai mera...
3   [daging ayam, gula, kol, minyak, tepung ayam, ...
4   [ketumbar bubuk, kulit ayam, bawang putih, min...
5   [kecap manis, bawang putih, kemiri, serai, min...
6   [merica, gula, garam dan, jeruk nipis, bawang ...
7   [ayam, saos, bawang daun, bawang putih, cabe i...
8   [maizena cairkan, bawang putih, kecap manis, d...
9   [tepung, saos sambal, ayam, gula, tomat uk, bp...
10  [lengkuas, sereh, ketumbar, bahan sambal, bawa...
11  [royco, kecap, daun jeruk, garam, gula, ketumb...
12  [lengkuas, sereh, sedikit jahe, bawang putih, ...
13  [cabe rawit, lengkuas, ayam, garam, gula, daun...
14  [fillet ayam, tepung bumbu, garam sck, telur a...
15  [btg sereh, kecap, gula, btr jeruk, kaldu, baw...
16  [aku beli, cabe rawit, bumbu ayam, garam, bawa...
17  [mangkok makaroni, garam, wortel, ceker ayam, ...
18  [kunyit, daun jeruk, jahe, garam, bawang putih...
19  [garam, tepung tapioka, bawang putih, merica, ...

                                     ingredients_join
0   cabe rawit daun garam sereh daun salam bawang ...
1   daun jeruk garam ketumbar bawang putih minyak ...
2   garam gula bawang putih minyak cabai merah baw...
3   daging ayam gula kol minyak tepung ayam timun ...
4   ketumbar bubuk kulit ayam bawang putih minyak ...
5   kecap manis bawang putih kemiri serai minyak t...
6   merica gula garam dan jeruk nipis bawang putih...
7   ayam saos bawang daun bawang putih cabe ijo me...
8   maizena cairkan bawang putih kecap manis dada ...
9   tepung saos sambal ayam gula tomat uk bputih m...
10  lengkuas sereh ketumbar bahan sambal bawang pu...
11  royco kecap daun jeruk garam gula ketumbar dau...
12  lengkuas sereh sedikit jahe bawang putih kecap...
13  cabe rawit lengkuas ayam garam gula daun salam...
14  fillet ayam tepung bumbu garam sck telur ayam ...
15  btg sereh kecap gula btr jeruk kaldu bawang pu...
16  aku beli cabe rawit bumbu ayam garam bawang p ...
17  mangkok makaroni garam wortel ceker ayam teh b...
18  kunyit daun jeruk jahe garam bawang putih grm ...
19  garam tepung tapioka bawang putih merica bawan...

In [100]:
df.to_csv("resep_final_bgst.csv", index=False, encoding="utf-8-sig")

In [101]:
import pandas as pd
import ast

# =========================
# LOAD DATA
# =========================
df = pd.read_csv("resep_cleaned.csv")

print(df.columns)


# =========================
# UBAH STRING LIST -> LIST
# =========================
def convert_to_list(x):
    try:
        return ast.literal_eval(x)
    except:
        return []

df["Ingredients Cleaned"] = df["Ingredients Cleaned"].apply(convert_to_list)


# =========================
# PHRASE YANG HARUS DIHAPUS
# (noise / bukan bahan utama)
# =========================
remove_phrases = {
    "aku beli",
    "bahan sambal",
    "penyedap rasa",
    "garam dan",
    "maizena cairkan",
    "tomat uk",
    "garam sck",
    "teh b",
    "mangkok makaroni",
    "sedikit jahe",
    "sedikit gula",
    "sedikit garam"
}


# =========================
# NORMALISASI PHRASE
# =========================
normalize_phrases = {
    "saos": "saus",
    "cabe": "cabai",
    "cabe ijo": "cabai hijau",
    "ijo": "hijau",
    "bputih": "bawang putih",
    "bmerah": "bawang merah",
    "btg sereh": "sereh",
    "btr jeruk": "jeruk",
    "grm": "garam",
    "daun": "",  # hanya jika berdiri sendiri
}


# =========================
# WORD NOISE KECIL
# =========================
small_noise = {
    "dan", "atau", "uk", "sck",
    "btg", "btr", "aku", "beli",
    "sedikit", "secukupnya",
    "bagian", "gelas", "ekor",
    "air", "buah", "butir",
    "siung", "sendok", "sdm", "sdt",
    "kg", "gram", "ml", "liter",
    "cup", "bungkus"
}


# =========================
# CLEANING FINAL
# =========================
def clean_phrase_level(items):
    result = []

    for item in items:
        item = str(item).lower().strip()

        # skip phrase noise penuh
        if item in remove_phrases:
            continue

        # normalisasi phrase
        for old, new in normalize_phrases.items():
            if old in item:
                item = item.replace(old, new)

        # split kata
        words = item.split()

        # hapus word noise
        words = [w for w in words if w not in small_noise]

        item = " ".join(words).strip()

        # skip kosong
        if item == "":
            continue

        # skip terlalu pendek
        if len(item) <= 2:
            continue

        result.append(item)

    # hapus duplikat
    result = list(dict.fromkeys(result))

    return result


# =========================
# PROSES CLEANING
# =========================
df["Ingredients Final"] = df["Ingredients Cleaned"].apply(clean_phrase_level)


# =========================
# KOLOM UNTUK TF-IDF
# =========================
df["ingredients_join"] = df["Ingredients Final"].apply(
    lambda x: " ".join(x)
)


# =========================
# HAPUS DUPLIKAT FINAL
# =========================
df = df.drop_duplicates(
    subset=["Title Cleaned", "ingredients_join"]
)


# =========================
# SIMPAN FILE FINAL
# =========================
df.to_csv(
    "resep_final_ready.csv",
    index=False,
    encoding="utf-8-sig"
)

print("SELESAI")
print("Dataset final sudah siap untuk TF-IDF")

print(df[
    ["Title Cleaned", "Ingredients Final", "ingredients_join"]
].head(20))

Index(['Title', 'Ingredients', 'Steps', 'Loves', 'URL', 'Category',
       'Title Cleaned', 'Total Ingredients', 'Ingredients Cleaned',
       'Total Steps', 'ingredients_join'],
      dtype='str')
SELESAI
Dataset final sudah siap untuk TF-IDF
                             Title Cleaned  \
0                         ayam woku manado
1                 ayam goreng tulang lunak
2                         ayam cabai kawin
3                              ayam geprek
4                              minyak ayam
5                          nasi bakar ayam
6                  ayam saus hintalu jaruk
7            ayam saos teriyaki lada hitam
8                               steak ayam
9              ayam saos asam manis simple
10              mie ayam homemade by suami
11  ayam bakar pedas manis resep nila sari
12      semur ayam kentang ala mama kirana
13                              ayam suwir
14                      ayam goreng tepung
15                 tulang ayam pedas manis
16                     ayam penyet rumahan
17                                sop ayam
18                              ayam suwir
19                   nugget ayam home made

                                    Ingredients Final  \
0   [cabai rawit, ikat, garam, sereh, salam, bawan...
1   [jeruk, garam, ketumbar, bawang putih, minyak,...
2   [garam, gula, bawang putih, minyak, cabai mera...
3   [daging ayam, gula, kol, minyak, tepung ayam, ...
4   [ketumbar bubuk, cincang kasar, geprek, kulit ...
5   [kecap manis, bawang putih, kemiri, cm serai, ...
6   [bks merica, gula, jeruk nipis, bawang putih, ...
7   [ayam, saus, bawang, bawang putih, cabai hijau...
8   [bawang putih, kecap manis, dada ayam, maizena...
9   [tepung, saus sambal, ayam, gula, bawang putih...
10  [lengkuas, sereh, ketumbar, bawang putih, kemi...
11  [royco, kecap, jeruk, garam, gula, ketumbar, s...
12  [lengkuas, sereh, bawang putih, kecap manis, k...
13  [cabai rawit, lengkuas, ayam, garam, gula, pen...
14  [fillet ayam, tepung bumbu, telur ayam, minya ...
15  [sereh, kecap, gula, jeruk, kaldu, bawang puti...
16  [cabai rawit, bumbu ayam, garam, bawang p, btn...
17  [garam, wortel iris, ceker ayam, teh, bawang p...
18  [cm kunyit, jeruk, cm jahe, garam, bawang puti...
19  [garam, tepung tapioka, bawang putih, merica, ...

                                     ingredients_join
0   cabai rawit ikat garam sereh salam bawang puti...
1   jeruk garam ketumbar bawang putih minyak kemir...
2   garam gula bawang putih minyak cabai merah baw...
3   daging ayam gula kol minyak tepung ayam timun ...
4   ketumbar bubuk cincang kasar geprek kulit ayam...
5   kecap manis bawang putih kemiri cm serai minya...
6   bks merica gula jeruk nipis bawang putih minya...
7   ayam saus bawang bawang putih cabai hijau ment...
8   bawang putih kecap manis dada ayam maizena jam...
9   tepung saus sambal ayam gula bawang putih iris...
10  lengkuas sereh ketumbar bawang putih kemiri te...
11  royco kecap jeruk garam gula ketumbar salam la...
12  lengkuas sereh bawang putih kecap manis kemiri...
13  cabai rawit lengkuas ayam garam gula penyedap ...
14   fillet ayam tepung bumbu telur ayam minya goreng
15  sereh kecap gula jeruk kaldu bawang putih lbr ...
16  cabai rawit bumbu ayam garam bawang p btng ser...
17  garam wortel iris ceker ayam teh bawang putih ...
18  cm kunyit jeruk cm jahe garam bawang putih gar...
19  garam tepung tapioka bawang putih merica bawan...

In [102]:
import pandas as pd
import ast

# load data
df = pd.read_csv("resep_cleaned.csv")

# ubah string list jadi list asli
def convert_to_list(x):
    try:
        return ast.literal_eval(x)
    except:
        return []

df["Ingredients Cleaned"] = df["Ingredients Cleaned"].apply(convert_to_list)

# daftar bahan valid (whitelist)
valid_ingredients = {
    "ayam", "daging ayam", "fillet ayam", "ceker ayam",
    "bawang putih", "bawang merah", "bawang daun",
    "cabai rawit", "cabai merah", "cabai hijau",
    "garam", "gula", "minyak", "minyak goreng",
    "jahe", "kunyit", "lengkuas", "kemiri",
    "ketumbar", "merica", "serai", "sereh",
    "daun salam", "daun jeruk",
    "jeruk nipis", "tomat", "kol", "wortel",
    "tepung", "tepung ayam", "tepung tapioka",
    "tepung bumbu", "maizena",
    "telur", "kecap", "kecap manis",
    "saus", "saus sambal", "saus tiram",
    "kaldu", "jamur", "nasi", "makaroni"
}

# normalisasi kata
normalization = {
    "cabe": "cabai",
    "cabe ijo": "cabai hijau",
    "ijo": "hijau",
    "saos": "saus",
    "salam": "daun salam",
    "bputih": "bawang putih",
    "bmerah": "bawang merah",
    "minya": "minyak",
    "btg sereh": "sereh"
}

def clean_final(items):
    result = []

    for item in items:
        item = str(item).lower().strip()

        # normalisasi
        for old, new in normalization.items():
            if old in item:
                item = item.replace(old, new)

        # hanya simpan yang ada di whitelist
        if item in valid_ingredients:
            result.append(item)

    # hapus duplikat
    result = list(dict.fromkeys(result))
    return result

# proses final
df["Ingredients Final"] = df["Ingredients Cleaned"].apply(clean_final)

# gabung untuk TF-IDF
df["ingredients_join"] = df["Ingredients Final"].apply(
    lambda x: " ".join(x)
)

# hapus data kosong
df = df[df["ingredients_join"].str.strip() != ""]

# hapus duplikat
df = df.drop_duplicates(
    subset=["Title Cleaned", "ingredients_join"]
)

# simpan final
df.to_csv("resep_final_ready.csv", index=False, encoding="utf-8-sig")

print(df[["Title Cleaned", "Ingredients Final", "ingredients_join"]].head(20))
print("Dataset final benar-benar siap TF-IDF")

                             Title Cleaned  \
0                         ayam woku manado
1                 ayam goreng tulang lunak
2                         ayam cabai kawin
3                              ayam geprek
4                              minyak ayam
5                          nasi bakar ayam
6                  ayam saus hintalu jaruk
7            ayam saos teriyaki lada hitam
8                               steak ayam
9              ayam saos asam manis simple
10              mie ayam homemade by suami
11  ayam bakar pedas manis resep nila sari
12      semur ayam kentang ala mama kirana
13                              ayam suwir
14                      ayam goreng tepung
15                 tulang ayam pedas manis
16                     ayam penyet rumahan
17                                sop ayam
18                              ayam suwir
19                   nugget ayam home made

                                    Ingredients Final  \
0   [cabai rawit, garam, sereh, bawang putih, bawa...
1   [daun jeruk, garam, ketumbar, bawang putih, ke...
2   [garam, gula, bawang putih, cabai merah, bawan...
3               [daging ayam, gula, kol, tepung ayam]
4                                [bawang putih, jahe]
5   [kecap manis, bawang putih, kemiri, tomat, baw...
6   [gula, jeruk nipis, bawang putih, cabai hijau,...
7   [bawang daun, bawang putih, cabai hijau, cabai...
8   [bawang putih, kecap manis, maizena, saus tira...
9             [saus sambal, gula, merica, saus tiram]
10  [lengkuas, sereh, ketumbar, bawang putih, kemi...
11  [kecap, daun jeruk, garam, gula, ketumbar, baw...
12  [lengkuas, sereh, bawang putih, kecap manis, k...
13  [cabai rawit, lengkuas, garam, gula, merica, b...
14         [fillet ayam, tepung bumbu, minyak goreng]
15  [sereh, kecap, gula, kaldu, bawang putih, bawa...
16  [cabai rawit, garam, bawang merah, cabai merah...
17  [garam, ceker ayam, bawang putih, bawang merah...
18    [daun jeruk, garam, bawang putih, bawang merah]
19  [garam, tepung tapioka, bawang putih, merica, ...

                                     ingredients_join
0   cabai rawit garam sereh bawang putih bawang me...
1   daun jeruk garam ketumbar bawang putih kemiri ...
2   garam gula bawang putih cabai merah bawang mer...
3                    daging ayam gula kol tepung ayam
4                                   bawang putih jahe
5   kecap manis bawang putih kemiri tomat bawang m...
6   gula jeruk nipis bawang putih cabai hijau caba...
7    bawang daun bawang putih cabai hijau cabai merah
8   bawang putih kecap manis maizena saus tiram ga...
9                  saus sambal gula merica saus tiram
10  lengkuas sereh ketumbar bawang putih kemiri da...
11  kecap daun jeruk garam gula ketumbar bawang me...
12  lengkuas sereh bawang putih kecap manis kemiri...
13  cabai rawit lengkuas garam gula merica bawang ...
14             fillet ayam tepung bumbu minyak goreng
15  sereh kecap gula kaldu bawang putih bawang mer...
16  cabai rawit garam bawang merah cabai merah jer...
17    garam ceker ayam bawang putih bawang merah ayam
18         daun jeruk garam bawang putih bawang merah
19  garam tepung tapioka bawang putih merica bawan...
Dataset final benar-benar siap TF-IDF

In [103]:
df.to_csv("resep_siap_pakai.csv", index=False, encoding="utf-8-sig")

print("File berhasil disimpan: resep_siap_pakai.csv")

File berhasil disimpan: resep_siap_pakai.csv

In [104]:
from collections import Counter

all_words = " ".join(df["ingredients_join"]).split()
freq = Counter(all_words)

print(freq.most_common(100))

[('bawang', 20100), ('merah', 11654), ('putih', 11527), ('garam', 10048), ('cabai', 7535), ('gula', 4261), ('rawit', 3683), ('kecap', 3593), ('jeruk', 2896), ('daun', 2321), ('manis', 2119), ('saus', 1982), ('tomat', 1917), ('merica', 1909), ('kemiri', 1896), ('jahe', 1709), ('ketumbar', 1602), ('telur', 1526), ('tiram', 1343), ('kunyit', 1239), ('lengkuas', 1128), ('sereh', 1010), ('serai', 994), ('wortel', 980), ('tepung', 751), ('ayam', 739), ('nipis', 735), ('hijau', 710), ('kaldu', 449), ('sambal', 342), ('kol', 311), ('tapioka', 275), ('bumbu', 190), ('daging', 155), ('maizena', 134), ('salam', 99), ('jamur', 47), ('nasi', 41), ('ceker', 29), ('fillet', 25), ('minyak', 6), ('goreng', 6), ('makaroni', 6)]

In [105]:
phrase_map = {
    "bawang putih": "bawang_putih",
    "bawang merah": "bawang_merah",
    "cabai rawit": "cabai_rawit",
    "cabai merah": "cabai_merah",
    "cabai hijau": "cabai_hijau",
    "jeruk nipis": "jeruk_nipis",
    "saus tiram": "saus_tiram",
    "saus sambal": "saus_sambal",
    "kecap manis": "kecap_manis",
    "daun salam": "daun_salam",
    "daun jeruk": "daun_jeruk",
    "minyak goreng": "minyak_goreng",
    "tepung tapioka": "tepung_tapioka",
    "tepung bumbu": "tepung_bumbu",
    "fillet ayam": "fillet_ayam",
    "ceker ayam": "ceker_ayam",
    "daging ayam": "daging_ayam"
}

def apply_phrase_map(text):
    text = str(text).lower()

    for old, new in phrase_map.items():
        text = text.replace(old, new)

    return text

df["ingredients_join"] = df["ingredients_join"].apply(apply_phrase_map)

print(df["ingredients_join"].head(10))

0    cabai_rawit garam sereh bawang_putih bawang_me...
1    daun_jeruk garam ketumbar bawang_putih kemiri ...
2    garam gula bawang_putih cabai_merah bawang_mer...
3                     daging_ayam gula kol tepung ayam
4                                    bawang_putih jahe
5    kecap_manis bawang_putih kemiri tomat bawang_m...
6    gula jeruk_nipis bawang_putih cabai_hijau caba...
7     bawang daun bawang_putih cabai_hijau cabai_merah
8    bawang_putih kecap_manis maizena saus_tiram ga...
9                   saus_sambal gula merica saus_tiram
Name: ingredients_join, dtype: str

In [106]:
from collections import Counter

all_words = " ".join(df["ingredients_join"]).split()
freq = Counter(all_words)

print(freq.most_common(50))

[('bawang_putih', 11527), ('garam', 10048), ('bawang_merah', 8512), ('gula', 4261), ('cabai_rawit', 3683), ('cabai_merah', 3142), ('daun_jeruk', 2161), ('kecap_manis', 2119), ('tomat', 1917), ('merica', 1909), ('kemiri', 1896), ('jahe', 1709), ('ketumbar', 1602), ('telur', 1526), ('kecap', 1474), ('saus_tiram', 1343), ('kunyit', 1239), ('lengkuas', 1128), ('sereh', 1010), ('serai', 994), ('wortel', 980), ('jeruk_nipis', 735), ('cabai_hijau', 710), ('ayam', 530), ('kaldu', 449), ('saus_sambal', 342), ('kol', 311), ('saus', 297), ('tepung', 286), ('tepung_tapioka', 275), ('tepung_bumbu', 190), ('daging_ayam', 155), ('maizena', 134), ('daun_salam', 99), ('bawang', 61), ('daun', 61), ('jamur', 47), ('nasi', 41), ('ceker_ayam', 29), ('fillet_ayam', 25), ('minyak_goreng', 6), ('makaroni', 6)]

In [107]:
remove_last_noise = {
    "bawang",
    "daun"
}

def remove_small_noise(text):
    words = text.split()
    words = [w for w in words if w not in remove_last_noise]
    return " ".join(words)

df["ingredients_join"] = df["ingredients_join"].apply(remove_small_noise)

print(df["ingredients_join"].head(10))

0    cabai_rawit garam sereh bawang_putih bawang_me...
1    daun_jeruk garam ketumbar bawang_putih kemiri ...
2    garam gula bawang_putih cabai_merah bawang_mer...
3                     daging_ayam gula kol tepung ayam
4                                    bawang_putih jahe
5    kecap_manis bawang_putih kemiri tomat bawang_m...
6    gula jeruk_nipis bawang_putih cabai_hijau caba...
7                 bawang_putih cabai_hijau cabai_merah
8    bawang_putih kecap_manis maizena saus_tiram ga...
9                   saus_sambal gula merica saus_tiram
Name: ingredients_join, dtype: str

In [108]:
from collections import Counter

all_words = " ".join(df["ingredients_join"]).split()
freq = Counter(all_words)

print(freq.most_common(50))

[('bawang_putih', 11527), ('garam', 10048), ('bawang_merah', 8512), ('gula', 4261), ('cabai_rawit', 3683), ('cabai_merah', 3142), ('daun_jeruk', 2161), ('kecap_manis', 2119), ('tomat', 1917), ('merica', 1909), ('kemiri', 1896), ('jahe', 1709), ('ketumbar', 1602), ('telur', 1526), ('kecap', 1474), ('saus_tiram', 1343), ('kunyit', 1239), ('lengkuas', 1128), ('sereh', 1010), ('serai', 994), ('wortel', 980), ('jeruk_nipis', 735), ('cabai_hijau', 710), ('ayam', 530), ('kaldu', 449), ('saus_sambal', 342), ('kol', 311), ('saus', 297), ('tepung', 286), ('tepung_tapioka', 275), ('tepung_bumbu', 190), ('daging_ayam', 155), ('maizena', 134), ('daun_salam', 99), ('jamur', 47), ('nasi', 41), ('ceker_ayam', 29), ('fillet_ayam', 25), ('minyak_goreng', 6), ('makaroni', 6)]

In [109]:
df.head(20)

,Title,Ingredients,Steps,Loves,URL,Category,Title Cleaned,Total Ingredients,Ingredients Cleaned,Total Steps,ingredients_join,Ingredients Final
0,Ayam Woku Manado,1 Ekor Ayam Kampung (potong 12)--2 Buah Jeruk ...,1) Cuci bersih ayam dan tiriskan. Lalu peras j...,1,https://cookpad.com/id/resep/4473027-ayam-woku...,ayam,ayam woku manado,14,"[cabe rawit, ikat daun, garam, sereh, daun sal...",7,cabai_rawit garam sereh bawang_putih bawang_me...,"[cabai rawit, garam, sereh, bawang putih, bawa..."
1,Ayam goreng tulang lunak,1 kg ayam (dipotong sesuai selera jangan kecil...,"1) Haluskan bumbu2nya (BaPut, ketumbar, kemiri...",1,https://cookpad.com/id/resep/4471956-ayam-gore...,ayam,ayam goreng tulang lunak,11,"[daun jeruk, garam, ketumbar, air, bawang puti...",5,daun_jeruk garam ketumbar bawang_putih kemiri ...,"[daun jeruk, garam, ketumbar, bawang putih, ke..."
2,Ayam cabai kawin,1/4 kg ayam--3 buah cabai hijau besar--7 buah ...,1) Panaskan minyak di dalam wajan. Setelah min...,2,https://cookpad.com/id/resep/4473057-ayam-caba...,ayam,ayam cabai kawin,10,"[garam, gula, air, bawang putih, minyak, cabai...",3,garam gula bawang_putih cabai_merah bawang_mer...,"[garam, gula, bawang putih, cabai merah, bawan..."
3,Ayam Geprek,250 gr daging ayam (saya pakai fillet)--Secuku...,1) Goreng ayam seperti ayam krispi\n2) Ulek se...,10,https://cookpad.com/id/resep/4473023-ayam-geprek,ayam,ayam geprek,7,"[daging ayam, gula, kol, minyak, tepung ayam, ...",3,daging_ayam gula kol tepung ayam,"[daging ayam, gula, kol, tepung ayam]"
4,Minyak Ayam,400 gr kulit ayam & lemaknya--8 siung bawang p...,1) Cuci bersih kulit ayam. Sisihkan\n2) Ambil ...,4,https://cookpad.com/id/resep/4427438-minyak-ayam,ayam,minyak ayam,5,"[ketumbar bubuk, cincang kasar, geprek, kulit ...",6,bawang_putih jahe,"[bawang putih, jahe]"
5,Nasi Bakar Ayam,"1 piring nasi--¹/⁴ fillet ayam, potong kotak, ...","1) Tumis bumbu halus, masukkan daun salam, ser...",1,https://cookpad.com/id/resep/4472552-nasi-baka...,ayam,nasi bakar ayam,23,"[kecap manis, bawang putih, kemiri, cm serai, ...",7,kecap_manis bawang_putih kemiri tomat bawang_m...,"[kecap manis, bawang putih, kemiri, tomat, baw..."
6,Ayam Saus Hintalu Jaruk,1/2 Ekor ayam--2 Butir Hintalu Jaruk--1 Buah C...,1) Potong ayam menjadi kotak-kotak ukuran seda...,0,https://cookpad.com/id/resep/4437475-ayam-saus...,ayam,ayam saus hintalu jaruk,10,"[bks merica, gula, garam dan, jeruk nipis, baw...",7,gula jeruk_nipis bawang_putih cabai_hijau caba...,"[gula, jeruk nipis, bawang putih, cabai hijau,..."
7,Ayam saos teriyaki Lada Hitam,Ayam bagian dada dan tulang--1 buah bawang bom...,1) Cara Buat :\n1. Sediakan teplon or wajan be...,0,https://cookpad.com/id/resep/4472877-ayam-saos...,ayam,ayam saos teriyaki lada hitam,13,"[ayam bagian, bungkus saos, air, bawang daun, ...",4,bawang_putih cabai_hijau cabai_merah,"[bawang daun, bawang putih, cabai hijau, cabai..."
8,Steak ayam,300 gr dada ayam fillet--1 sdm air jeruk nipis...,"1) Cuci bersih ayam, iris tipis melebar, renda...",6,https://cookpad.com/id/resep/4472822-steak-ayam,ayam,steak ayam,28,"[maizena cairkan, bawang putih, kecap manis, d...",6,bawang_putih kecap_manis maizena saus_tiram ga...,"[bawang putih, kecap manis, maizena, saus tira..."
9,Ayam Saos Asam Manis Simple,1/4 kg Ayam bagian dada fillet (Potong dadu)--...,1) Lumuri ayam yg sdh dipotong dadu dgn garam ...,6,https://cookpad.com/id/resep/4472901-ayam-saos...,ayam,ayam saos asam manis simple,11,"[bungkus tepung, saos sambal, ayam bagian, gul...",9,saus_sambal gula merica saus_tiram,"[saus sambal, gula, merica, saus tiram]"
10,Mie Ayam Homemade by suami😂😂😂,Bahan mie ayam :--1 kg tepung terigu proteiin ...,"1) Kocok telur masukan garam n minyak goreng,a...",0,https://cookpad.com/id/resep/4472541-mie-ayam-...,ayam,mie ayam homemade by suami,32,"[lengkuas, sereh, ketumbar, bahan sambal, bawa...",9,lengkuas sereh ketumbar bawang_putih kemiri da...,"[lengkuas, sereh, ketumbar, bawang putih, kemi..."
11,Ayam Bakar Pedas Manis Resep :Nila Sari,1 Ekor Ayam Broiler Ukuran Jumbo--Bumbu :--5 S...,1) Iris tipis bawang merah dan daun jeruk.\n2)...,8,https://cookpad.com/id/resep/4472362-ayam-baka...,ayam,ayam bakar pedas manis resep nila sari,18,"[royco, kecap, daun jeruk, garam, gula, ketumb...",8,kecap daun_jeruk garam gula ketumbar bawang_me...,"[kecap, daun jeruk, garam, gula, ketumbar, baw..."
12,Semur Ayam Kentang Ala Mama Kirana,1/2 Ekor ayam--Kentang--Bumbu Halus :--Bawang ...,1) Cuci bersih ayam lalu baluri dengan perasan...,2,https://cookpad.com/id/resep/4472563-semur-aya...,ayam,semur ayam kentang ala mama kirana,22,"[lengkuas, sereh, sedikit jahe, bawang putih, ...",9,lengkuas sereh bawang_putih kecap_manis kemiri...,"[lengkuas, sereh, bawang putih, kecap manis, k..."
13,Ayam suwir,300 gram Ayam suwir (sudah direbus/Goreng)--5 ...,"1) Haluskan semua bumbu kecuali tomat, lengkua...",0,https://cookpad.com/id/resep/4471653-ayam-suwir,ayam,ayam suwir,14,"[cabe rawit, lengkuas, gram ayam, garam, gula,...",7,cabai_rawit lengkuas garam gula merica bawang_...,"[cabai rawit, lengkuas, garam, gula, merica, b..."
14,Ayam goreng tepung,150 gr fillet ayam--5 sdm tepung bumbu serbagu...,"1) Cuci ayam, tiriskan beri perasan jeruk lemo...",1,https://cookpad.com/id/resep/4472498-ayam-gore...,ayam,ayam goreng tepung,5,"[fillet ayam, tepung bumbu, garam sck, telur a...",5,fillet_ayam tepung_bumbu minyak_goreng,"[fillet ayam, tepung bumbu, minyak goreng]"
15,Tulang Ayam Pedas Manis,1/2 kg tulang ayam bersihkan lalu potong--5 bh...,1) Setelah tulang ayam di bersihkan dan di pot...,3,https://cookpad.com/id/resep/4472409-tulang-ay...,ayam,tulang ayam pedas manis,16,"[btg sereh, kecap, ml air, gula, btr jeruk, ka...",6,sereh kecap gula kaldu bawang_putih bawang_mer...,"[sereh, kecap, gula, kaldu, bawang putih, bawa..."
16,Ayam penyet rumahan,1 ekr ayam negri cuci bersih ptng beri air jer...,"1) Ungkep ayam bersama bumbu jadi, daun salam,...",3,https://cookpad.com/id/resep/4472187-ayam-peny...,ayam,ayam penyet rumahan,14,"[aku beli, cabe rawit, bumbu ayam, garam, bawa...",5,cabai_rawit garam bawang_merah cabai_merah jer...,"[cabai rawit, garam, bawang merah, cabai merah..."
17,Sop ayam,1 kg ayam potong kecil kecil--1/2 kg ceker aya...,1) Tumis bawang merah dan bawang putih hingga ...,3,https://cookpad.com/id/resep/4472298-sop-ayam,ayam,sop ayam,14,"[mangkok makaroni, garam, wortel iris, ceker a...",9,garam ceker_ayam bawang_putih bawang_merah ayam,"[garam, ceker ayam, bawang putih, bawang merah..."
18,Ayam suwir,400 grm dada ayam--3 lembar daun jeruk--4 siun...,1) Rebus ayam sampai matang dan di suir suir.\...,0,https://cookpad.com/id/resep/4472222-ayam-suwir,ayam,ayam suwir,8,"[cm kunyit, daun jeruk, cm jahe, garam, bawang...",4,daun_jeruk garam bawang_putih bawang_merah,"[daun jeruk, garam, bawang putih, bawang merah]"
19,Nugget Ayam Home Made,1/4 kg ayam d fillet ambil dagingnya aja--1 bu...,1) Cuci bersih ayam. Setelah itu potong kecil2...,6,https://cookpad.com/id/resep/4472482-nugget-ay...,ayam,nugget ayam home made,10,"[garam, tepung tapioka, bawang putih, merica, ...",10,garam tepung_tapioka bawang_putih merica bawan...,"[garam, tepung tapioka, bawang putih, merica, ..."

In [110]:
df.to_csv("resep_final_siap.csv", index=False, encoding="utf-8-sig")

In [111]:
type(df['Ingredients Final'][0])

list

In [114]:
df_final = df[['Title', 'Ingredients Final']].copy()
df_final.columns = ['recipe_name', 'ingredients']

In [115]:
df_final['ingredients_text'] = df_final['ingredients'].apply(lambda x: ' '.join(x))

In [116]:
df.to_csv("resep_final_siap2.csv", index=False, encoding="utf-8-sig")

In [118]:
df_final.head(10)

,recipe_name,ingredients,ingredients_text
0,Ayam Woku Manado,"[cabai rawit, garam, sereh, bawang putih, bawa...",cabai rawit garam sereh bawang putih bawang me...
1,Ayam goreng tulang lunak,"[daun jeruk, garam, ketumbar, bawang putih, ke...",daun jeruk garam ketumbar bawang putih kemiri ...
2,Ayam cabai kawin,"[garam, gula, bawang putih, cabai merah, bawan...",garam gula bawang putih cabai merah bawang mer...
3,Ayam Geprek,"[daging ayam, gula, kol, tepung ayam]",daging ayam gula kol tepung ayam
4,Minyak Ayam,"[bawang putih, jahe]",bawang putih jahe
5,Nasi Bakar Ayam,"[kecap manis, bawang putih, kemiri, tomat, baw...",kecap manis bawang putih kemiri tomat bawang m...
6,Ayam Saus Hintalu Jaruk,"[gula, jeruk nipis, bawang putih, cabai hijau,...",gula jeruk nipis bawang putih cabai hijau caba...
7,Ayam saos teriyaki Lada Hitam,"[bawang daun, bawang putih, cabai hijau, cabai...",bawang daun bawang putih cabai hijau cabai merah
8,Steak ayam,"[bawang putih, kecap manis, maizena, saus tira...",bawang putih kecap manis maizena saus tiram ga...
9,Ayam Saos Asam Manis Simple,"[saus sambal, gula, merica, saus tiram]",saus sambal gula merica saus tiram

In [120]:
df_final['ingredients'] = df_final['ingredients'].apply(
    lambda lst: [i.replace(' ', '_') for i in lst]
)

In [121]:
normalisasi = {
    'daging_ayam': 'ayam',
    'bawang_daun': 'daun_bawang'
}

df_final['ingredients'] = df_final['ingredients'].apply(
    lambda lst: [normalisasi.get(i, i) for i in lst]
)

In [122]:
df_final['ingredients_text'] = df_final['ingredients'].apply(
    lambda x: ' '.join(x)
)

In [123]:
df_final.head(10)

,recipe_name,ingredients,ingredients_text
0,Ayam Woku Manado,"[cabai_rawit, garam, sereh, bawang_putih, bawa...",cabai_rawit garam sereh bawang_putih bawang_me...
1,Ayam goreng tulang lunak,"[daun_jeruk, garam, ketumbar, bawang_putih, ke...",daun_jeruk garam ketumbar bawang_putih kemiri ...
2,Ayam cabai kawin,"[garam, gula, bawang_putih, cabai_merah, bawan...",garam gula bawang_putih cabai_merah bawang_mer...
3,Ayam Geprek,"[ayam, gula, kol, tepung_ayam]",ayam gula kol tepung_ayam
4,Minyak Ayam,"[bawang_putih, jahe]",bawang_putih jahe
5,Nasi Bakar Ayam,"[kecap_manis, bawang_putih, kemiri, tomat, baw...",kecap_manis bawang_putih kemiri tomat bawang_m...
6,Ayam Saus Hintalu Jaruk,"[gula, jeruk_nipis, bawang_putih, cabai_hijau,...",gula jeruk_nipis bawang_putih cabai_hijau caba...
7,Ayam saos teriyaki Lada Hitam,"[daun_bawang, bawang_putih, cabai_hijau, cabai...",daun_bawang bawang_putih cabai_hijau cabai_merah
8,Steak ayam,"[bawang_putih, kecap_manis, maizena, saus_tira...",bawang_putih kecap_manis maizena saus_tiram ga...
9,Ayam Saos Asam Manis Simple,"[saus_sambal, gula, merica, saus_tiram]",saus_sambal gula merica saus_tiram

In [124]:
df.to_csv("resep_siap_pakai3.csv", index=False, encoding="utf-8-sig")

In [125]:
type(df_final['ingredients'].iloc[0])

list

In [126]:
df_final[['recipe_name', 'ingredients']].head(10)

,recipe_name,ingredients
0,Ayam Woku Manado,"[cabai_rawit, garam, sereh, bawang_putih, bawa..."
1,Ayam goreng tulang lunak,"[daun_jeruk, garam, ketumbar, bawang_putih, ke..."
2,Ayam cabai kawin,"[garam, gula, bawang_putih, cabai_merah, bawan..."
3,Ayam Geprek,"[ayam, gula, kol, tepung_ayam]"
4,Minyak Ayam,"[bawang_putih, jahe]"
5,Nasi Bakar Ayam,"[kecap_manis, bawang_putih, kemiri, tomat, baw..."
6,Ayam Saus Hintalu Jaruk,"[gula, jeruk_nipis, bawang_putih, cabai_hijau,..."
7,Ayam saos teriyaki Lada Hitam,"[daun_bawang, bawang_putih, cabai_hijau, cabai..."
8,Steak ayam,"[bawang_putih, kecap_manis, maizena, saus_tira..."
9,Ayam Saos Asam Manis Simple,"[saus_sambal, gula, merica, saus_tiram]"

In [127]:
df_final[df_final['ingredients'].apply(len) == 0]

Empty DataFrame
Columns: [recipe_name, ingredients, ingredients_text]
Index: []

In [128]:
df_final['ingredients_text'] = df_final['ingredients'].apply(lambda x: ' '.join(x))

In [129]:
from sklearn.feature_extraction.text import TfidfVectorizer

tfidf = TfidfVectorizer()
X = tfidf.fit_transform(df_final['ingredients_text'])

In [130]:
df.to_csv("resep_clean.csv", index=False, encoding="utf-8-sig")